- name: "bug"
  color: "d73a4a"
  description: "Bug or unexpected behavior."
- name: "critical"
  color: "b60205"
  description: "Breaking or high-impact issue."
- name: "high priority"
  color: "ffab70"
  description: "Priority work to address soon."
- name: "medium priority"
  color: "f9d0c4"
  description: "Medium importance."
- name: "low priority"
  color: "c2e0c6"
  description: "Low-impact or nice-to-have."
- name: "blocked"
  color: "5319e7"
  description: "Waiting on external dependency."
- name: "needs triage"
  color: "fbca04"
  description: "Requires review/triage."
- name: "confirmed"
  color: "0e8a16"
  description: "Issue reproduced and confirmed."
- name: "wontfix"
  color: "ffffff"
  description: "Will not be fixed (explain in comment)."
- name: "duplicate"
  color: "cccccc"
  description: "Duplicate of another issue."
- name: "good first issue"
  color: "7057ff"
  description: "Easy, great for newcomers."
- name: "beginner"
  color: "8bd3dd"
  description: "Low difficulty for new contributors."
- name: "easy"
  color: "0e8a16"
  description: "Quick, straightforward change."
- name: "moderate"
  color: "f7c6c7"
  description: "Medium effort."
- name: "hard"
  color: "d4c5f9"
  description: "Significant work required."
- name: "research"
  color: "ffd7b5"
  description: "Needs investigation/proof-of-concept."
- name: "spike"
  color: "c2e0c6"
  description: "Timeboxed experiment."
- name: "heavy refactor"
  color: "e99695"
  description: "Large structural changes."
- name: "follow-up"
  color: "fbca04"
  description: "Subsequent task after initial PR."
- name: "help wanted"
  color: "008672"
  description: "Contribution welcome."
- name: "enhancement"
  color: "a2eeef"
  description: "New feature or enhancement."
- name: "feature request"
  color: "0e8a16"
  description: "User-suggested feature."
- name: "bugfix"
  color: "d73a4a"
  description: "Fix required for bug."
- name: "regression"
  color: "c2e0c6"
  description: "Behavior regressed from earlier."
- name: "performance"
  color: "f9d0c4"
  description: "Performance improvement needed."
- name: "optimization"
  color: "fbca04"
  description: "Code/resource optimization."
- name: "refactor"
  color: "0366d6"
  description: "Improve code structure without changing behavior."
- name: "test"
  color: "cfd3d7"
  description: "Add/modify tests."
- name: "ci"
  color: "6f42c1"
  description: "CI or workflow changes."
- name: "docs"
  color: "0a0a23"
  description: "Documentation changes."
- name: "tooling"
  color: "5319e7"
  description: "Dev tools or scripts."
- name: "accessibility"
  color: "ffdf6b"
  description: "Accessibility improvements."
- name: "api"
  color: "1d76db"
  description: "Backend API-related."
- name: "auth"
  color: "a7f3d0"
  description: "Authentication/authorization."
- name: "database"
  color: "f9d0c4"
  description: "DB schema or queries."
- name: "frontend"
  color: "f0e68c"
  description: "UI/front-end work."
- name: "backend"
  color: "0e8a16"
  description: "Server-side logic."
- name: "mobile"
  color: "ff7b00"
  description: "Mobile app-specific."
- name: "cli"
  color: "6f42c1"
  description: "Command-line tool."
- name: "docs-site"
  color: "0366d6"
  description: "Documentation website."
- name: "integrations"
  color: "9b8cff"
  description: "Third-party integrations."
- name: "plugin"
  color: "f6c2ff"
  description: "Plugins or extensions."
- name: "javascript"
  color: "f1e05a"
  description: "JS/Node projects."
- name: "typescript"
  color: "2b7489"
  description: "TypeScript-specific."
- name: "python"
  color: "3572A5"
  description: "Python issues."
- name: "ruby"
  color: "701516"
  description: "Ruby-specific."
- name: "java"
  color: "b07219"
  description: "Java issues."
- name: "csharp"
  color: "178600"
  description: "C#/.NET."
- name: "go"
  color: "00ADD8"
  description: "Go-related."
- name: "rust"
  color: "dea584"
  description: "Rust-specific."
- name: "php"
  color: "4F5D95"
  description: "PHP issues."
- name: "html"
  color: "e34c26"
  description: "HTML/CSS."
- name: "css"
  color: "563d7c"
  description: "Styling/CSS."
- name: "docker"
  color: "0db7ed"
  description: "Docker/containerization."
- name: "mentor needed"
  color: "bfe5bf"
  description: "Needs a mentor to guide contributor."
- name: "onboarding task"
  color: "a2f5a2"
  description: "Small intro tasks for new contributors."
- name: "up for grabs"
  color: "ffc107"
  description: "Anyone can take this."
- name: "needs spec"
  color: "ffb3b3"
  description: "Requires design/spec before starting."
- name: "acceptance criteria"
  color: "d4f1f9"
  description: "Clear done conditions required."
- name: "contribution docs"
  color: "6f42c1"
  description: "Improve contribution guidelines."
- name: "CODE_OF_CONDUCT"
  color: "6ec1ff"
  description: "CoC related updates."
- name: "onboarding docs"
  color: "c0ffee"
  description: "Add/expand newcomer docs."
- name: "docs: getting started"
  color: "0366d6"
  description: "Quickstart/tutorial content."
- name: "docs: API reference"
  color: "0a0a23"
  description: "API docs updates."
- name: "docs: examples"
  color: "e6f4ff"
  description: "Add example projects/snippets."
- name: "docs: architecture"
  color: "d9d9f3"
  description: "Explain architecture/design."
- name: "docs: migration"
  color: "ffd8b5"
  description: "Migration guides."
- name: "docs: troubleshooting"
  color: "ffdf6b"
  description: "Troubleshooting/FAQ."
- name: "docs: changelog"
  color: "f1c0e8"
  description: "Changelog updates."
- name: "docs: glossary"
  color: "c2f0c2"
  description: "Define terms used."
- name: "unit tests"
  color: "1d76db"
  description: "Add/modify unit tests."
- name: "integration tests"
  color: "f9d0c4"
  description: "Integration or e2e tests."
- name: "flaky test"
  color: "ff69b4"
  description: "Flaky or unstable tests."
- name: "lint"
  color: "ffcc00"
  description: "Linting/style fixes."
- name: "security tests"
  color: "b60205"
  description: "Add security checks."
- name: "code coverage"
  color: "0e8a16"
  description: "Improve test coverage."
- name: "design"
  color: "c2e0c6"
  description: "Design work or mockups."
- name: "ux"
  color: "ffb3c6"
  description: "User experience improvements."
- name: "accessibility: a11y"
  color: "ffdf6b"
  description: "Accessibility fixes."
- name: "responsive"
  color: "6f42c1"
  description: "Responsive UI fixes."
- name: "iconography"
  color: "f6c2ff"
  description: "Icons/assets updates."
- name: "localization"
  color: "87bdd8"
  description: "i18n / translations."
- name: "security"
  color: "b60205"
  description: "Security vulnerability."
- name: "privacy"
  color: "ffdf6b"
  description: "Privacy/data handling."
- name: "dependency upgrade"
  color: "0db7ed"
  description: "Update dependencies safely."
- name: "secret leak"
  color: "000000"
  description: "Secrets exposed (handle privately)."
- name: "build"
  color: "c2f0c2"
  description: "Build system issues."
- name: "packaging"
  color: "f0ad4e"
  description: "Release/package tasks."
- name: "deployment"
  color: "2b8cbe"
  description: "Deployment/process changes."
- name: "release"
  color: "6f42c1"
  description: "Release notes / tagging."
- name: "dockerize"
  color: "0db7ed"
  description: "Containerize app."
- name: "helm / k8s"
  color: "326de6"
  description: "Kubernetes manifests."
- name: "good first issue: docs"
  color: "7057ff"
  description: "Beginner-friendly docs task."
- name: "good first issue: bug"
  color: "8bd3dd"
  description: "Small bug fix for new contributors."
- name: "good first issue: tests"
  color: "cfd3d7"
  description: "Add simple test."
- name: "mentored: medium"
  color: "a2f5a2"
  description: "Mentor-guided medium task."
- name: "mentored: advanced"
  color: "f7c6c7"
  description: "Advanced task with mentor support."
- name: "community task"
  color: "ffd7b5"
  description: "Community-focused work."
- name: "chore"
  color: "eb6420"
  description: "Routine maintenance tasks."
- name: "housekeeping"
  color: "cfcfcf"
  description: "Cleanup, remove unused code/assets."
