# Additional 100 Labels for Better Issue/PR Categorization

# Project Categories
- name: "web-app"
  color: "1d76db"
  description: "Web application related."

- name: "mobile-app"
  color: "ff7b00"
  description: "Mobile application development."

- name: "desktop-app"
  color: "6f42c1"
  description: "Desktop application work."

- name: "game"
  color: "ff69b4"
  description: "Game development."

- name: "library"
  color: "0366d6"
  description: "Library or SDK development."

- name: "framework"
  color: "0e8a16"
  description: "Framework development."

- name: "plugin"
  color: "f6c2ff"
  description: "Plugin or extension work."

- name: "api"
  color: "1d76db"
  description: "API development."

- name: "microservice"
  color: "00d4aa"
  description: "Microservice architecture."

- name: "monolith"
  color: "ff6b6b"
  description: "Monolithic application."

# Technology Stack
- name: "react"
  color: "61dafb"
  description: "React.js related."

- name: "vue"
  color: "4fc08d"
  description: "Vue.js related."

- name: "angular"
  color: "dd0031"
  description: "Angular related."

- name: "svelte"
  color: "ff3e00"
  description: "Svelte related."

- name: "nextjs"
  color: "000000"
  description: "Next.js related."

- name: "nuxt"
  color: "00c58e"
  description: "Nuxt.js related."

- name: "gatsby"
  color: "663399"
  description: "Gatsby related."

- name: "express"
  color: "000000"
  description: "Express.js related."

- name: "fastify"
  color: "202020"
  description: "Fastify related."

- name: "koa"
  color: "33333d"
  description: "Koa.js related."

# Database & Storage
- name: "mysql"
  color: "4479a1"
  description: "MySQL database."

- name: "postgresql"
  color: "336791"
  description: "PostgreSQL database."

- name: "mongodb"
  color: "47a248"
  description: "MongoDB database."

- name: "redis"
  color: "dc382d"
  description: "Redis cache/database."

- name: "sqlite"
  color: "003b57"
  description: "SQLite database."

- name: "elasticsearch"
  color: "005571"
  description: "Elasticsearch related."

- name: "graphql"
  color: "e10098"
  description: "GraphQL related."

- name: "rest-api"
  color: "ff6b6b"
  description: "REST API development."

- name: "websocket"
  color: "ffa500"
  description: "WebSocket implementation."

- name: "grpc"
  color: "244c5c"
  description: "gRPC implementation."

# Cloud & Infrastructure
- name: "aws"
  color: "ff9900"
  description: "Amazon Web Services."

- name: "azure"
  color: "0078d4"
  description: "Microsoft Azure."

- name: "gcp"
  color: "4285f4"
  description: "Google Cloud Platform."

- name: "heroku"
  color: "430098"
  description: "Heroku deployment."

- name: "vercel"
  color: "000000"
  description: "Vercel deployment."

- name: "netlify"
  color: "00c7b7"
  description: "Netlify deployment."

- name: "kubernetes"
  color: "326ce5"
  description: "Kubernetes related."

- name: "terraform"
  color: "7b42bc"
  description: "Terraform infrastructure."

- name: "ansible"
  color: "ee0000"
  description: "Ansible automation."

- name: "jenkins"
  color: "d24939"
  description: "Jenkins CI/CD."

# Development Tools
- name: "vscode"
  color: "007acc"
  description: "VS Code related."

- name: "webstorm"
  color: "000000"
  description: "WebStorm related."

- name: "vim"
  color: "019733"
  description: "Vim editor."

- name: "emacs"
  color: "7f5ab6"
  description: "Emacs editor."

- name: "git"
  color: "f05032"
  description: "Git version control."

- name: "github"
  color: "181717"
  description: "GitHub specific."

- name: "gitlab"
  color: "fca326"
  description: "GitLab specific."

- name: "bitbucket"
  color: "0052cc"
  description: "Bitbucket specific."

- name: "npm"
  color: "cb3837"
  description: "NPM package manager."

- name: "yarn"
  color: "2c8ebb"
  description: "Yarn package manager."

# Testing & Quality
- name: "jest"
  color: "c21325"
  description: "Jest testing framework."

- name: "mocha"
  color: "8d6748"
  description: "Mocha testing framework."

- name: "cypress"
  color: "17202c"
  description: "Cypress e2e testing."

- name: "playwright"
  color: "2ead33"
  description: "Playwright testing."

- name: "puppeteer"
  color: "40b5a4"
  description: "Puppeteer automation."

- name: "selenium"
  color: "43b02a"
  description: "Selenium testing."

- name: "karma"
  color: "0a9fd8"
  description: "Karma test runner."

- name: "jasmine"
  color: "8a4182"
  description: "Jasmine testing."

- name: "vitest"
  color: "6e9f18"
  description: "Vitest testing."

- name: "testing-library"
  color: "e33332"
  description: "Testing Library."

# Performance & Monitoring
- name: "lighthouse"
  color: "f44b21"
  description: "Lighthouse performance."

- name: "web-vitals"
  color: "4285f4"
  description: "Web Vitals metrics."

- name: "bundle-size"
  color: "ff6b6b"
  description: "Bundle size optimization."

- name: "memory-leak"
  color: "ff4757"
  description: "Memory leak issues."

- name: "profiling"
  color: "ffa502"
  description: "Performance profiling."

- name: "monitoring"
  color: "2ed573"
  description: "Application monitoring."

- name: "logging"
  color: "ff6348"
  description: "Logging implementation."

- name: "analytics"
  color: "ff9ff3"
  description: "Analytics integration."

- name: "metrics"
  color: "54a0ff"
  description: "Metrics collection."

- name: "alerting"
  color: "ff3838"
  description: "Alert system."

# Security & Compliance
- name: "owasp"
  color: "000000"
  description: "OWASP security guidelines."

- name: "cors"
  color: "ff6b6b"
  description: "CORS configuration."

- name: "csp"
  color: "ffa502"
  description: "Content Security Policy."

- name: "https"
  color: "2ed573"
  description: "HTTPS implementation."

- name: "ssl"
  color: "ff6348"
  description: "SSL/TLS certificates."

- name: "encryption"
  color: "ff9ff3"
  description: "Data encryption."

- name: "authentication"
  color: "54a0ff"
  description: "User authentication."

- name: "authorization"
  color: "5f27cd"
  description: "User authorization."

- name: "jwt"
  color: "00d2d3"
  description: "JWT tokens."

- name: "oauth"
  color: "ff9ff3"
  description: "OAuth implementation."

# Data & Analytics
- name: "data-processing"
  color: "ff6b6b"
  description: "Data processing tasks."

- name: "etl"
  color: "ffa502"
  description: "ETL pipeline."

- name: "data-visualization"
  color: "2ed573"
  description: "Data visualization."

- name: "machine-learning"
  color: "ff6348"
  description: "Machine learning."

- name: "ai"
  color: "ff9ff3"
  description: "Artificial intelligence."

- name: "nlp"
  color: "54a0ff"
  description: "Natural language processing."

- name: "computer-vision"
  color: "5f27cd"
  description: "Computer vision."

- name: "deep-learning"
  color: "00d2d3"
  description: "Deep learning."

- name: "neural-network"
  color: "ff9ff3"
  description: "Neural networks."

- name: "tensorflow"
  color: "ff6b00"
  description: "TensorFlow framework."

# UI/UX Categories
- name: "ui-component"
  color: "ff6b6b"
  description: "UI component development."

- name: "design-system"
  color: "ffa502"
  description: "Design system work."

- name: "wireframe"
  color: "2ed573"
  description: "Wireframe creation."

- name: "prototype"
  color: "ff6348"
  description: "Prototype development."

- name: "mockup"
  color: "ff9ff3"
  description: "Design mockups."

- name: "animation"
  color: "54a0ff"
  description: "CSS/JS animations."

- name: "interaction"
  color: "5f27cd"
  description: "User interactions."

- name: "navigation"
  color: "00d2d3"
  description: "Navigation design."

- name: "layout"
  color: "ff9ff3"
  description: "Page layout work."

- name: "typography"
  color: "ff6b00"
  description: "Typography improvements."

# Workflow & Process
- name: "code-review"
  color: "ff6b6b"
  description: "Code review process."

- name: "pull-request"
  color: "ffa502"
  description: "Pull request related."

- name: "merge"
  color: "2ed573"
  description: "Merge conflicts/issues."

- name: "rebase"
  color: "ff6348"
  description: "Git rebase work."

- name: "squash"
  color: "ff9ff3"
  description: "Commit squashing."

- name: "cherry-pick"
  color: "54a0ff"
  description: "Cherry-pick commits."

- name: "hotfix"
  color: "5f27cd"
  description: "Hotfix deployment."

- name: "rollback"
  color: "00d2d3"
  description: "Rollback changes."

- name: "branch-strategy"
  color: "ff9ff3"
  description: "Git branching strategy."

- name: "release-strategy"
  color: "ff6b00"
  description: "Release management."

# Community & Contribution
- name: "hacktoberfest"
  color: "ff6b6b"
  description: "Hacktoberfest related."

- name: "gsoc"
  color: "ffa502"
  description: "Google Summer of Code."

- name: "outreachy"
  color: "2ed573"
  description: "Outreachy program."

- name: "mentorship"
  color: "ff6348"
  description: "Mentorship program."

- name: "workshop"
  color: "ff9ff3"
  description: "Workshop or tutorial."

- name: "conference"
  color: "54a0ff"
  description: "Conference related."

- name: "meetup"
  color: "5f27cd"
  description: "Community meetup."

- name: "blog"
  color: "00d2d3"
  description: "Blog post content."

- name: "tutorial"
  color: "ff9ff3"
  description: "Tutorial creation."

- name: "example"
  color: "ff6b00"
  description: "Code examples."

# Maintenance & Operations
- name: "backup"
  color: "ff6b6b"
  description: "Backup procedures."

- name: "migration"
  color: "ffa502"
  description: "Data/system migration."

- name: "upgrade"
  color: "2ed573"
  description: "System upgrade."

- name: "downtime"
  color: "ff6348"
  description: "Scheduled downtime."

- name: "maintenance"
  color: "ff9ff3"
  description: "System maintenance."

- name: "cleanup"
  color: "54a0ff"
  description: "Code cleanup."

- name: "refactoring"
  color: "5f27cd"
  description: "Code refactoring."

- name: "optimization"
  color: "00d2d3"
  description: "Performance optimization."

- name: "monitoring"
  color: "ff9ff3"
  description: "System monitoring."

- name: "alerting"
  color: "ff6b00"
  description: "Alert configuration."